// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// config.h — keymap level (keymaps/vial/)
// Generated by QMK/Vial Wizard v5.6 on 2026-07-13
// ─────────────────────────────────────────────────────────────────
//
// This file configures Vial-specific behaviour.
// Hardware config (pins, matrix) lives in keyboard.json, not here.
//
#pragma once

// ── VIAL KEYBOARD UID ─────────────────────────────────────────────
// A unique 8-byte identifier for this keyboard in Vial's database.
// This ID is embedded in the firmware so Vial can identify the keyboard
// without needing an internet connection or a server lookup.
//
// IMPORTANT: Never reuse this UID across different keyboards.
// If you fork this keyboard definition for a new design, regenerate
// the UID by running from the vial-qmk root:
//   python3 util/vial_generate_keyboard_uid.py
//
#define VIAL_KEYBOARD_UID {0x93, 0x1A, 0xE4, 0x27, 0xC7, 0x1B, 0xFB, 0x47}

// ── VIAL SECURITY UNLOCK COMBO ───────────────────────────────────
// Vial requires you to hold a key combination to "unlock" the keyboard
// for programming. This protects against malicious USB hosts reprogramming
// your keyboard without your knowledge.
//
// Current combo: top-left key [row 0, col 0] + bottom-right key [row 2, col 2]
// Hold both keys simultaneously when Vial prompts for unlock.
//
// To change: replace the row/col numbers below with any 2+ keys
// that appear in your layout. Row and col are zero-based matrix positions.
//
#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }


// ── DEBOUNCE TIME (#27) ───────────────────────────────────────────
// Algorithm is set via DEBOUNCE_TYPE in rules.mk.
#define DEBOUNCE 5

// ── EEPROM MACRO SETTINGS (#1 #2) ────────────────────────────────
// Total macros exposed in Via/Vial.
#define DYNAMIC_KEYMAP_MACRO_COUNT 16
// Total byte budget for all macro content in EEPROM.
#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE 1024

// BOOTMAGIC: default (top-left key, row 0 col 0).



