// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// keymap.c — Vial default keymap
// Generated by QMK/Vial Wizard v5.6 on 2026-07-13
// ─────────────────────────────────────────────────────────────────
//
// This is a starting point — a basic QWERTY layout.
// You should remap keys using the Vial GUI after flashing.
// Vial stores your remapped layout in the keyboard's EEPROM,
// so you only need to reflash when changing features, not keycodes.
//
// HOW LAYERS WORK:
// Layer 0 is always active (base layer). Higher-numbered layers
// override lower ones when activated by a layer-switch key (MO, TG, etc).
// KC_TRNS on an upper layer means "fall through to the layer below".
// KC_NO on any layer means "do nothing / no keypress".
//
// MATRIX DIMENSIONS: 3 rows × 3 cols
// (Single board: 3 rows)
//
#include QMK_KEYBOARD_H



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // ── Layer 0: Base (QWERTY starting point) ────────────────────
    // Edit these keycodes directly, or use Vial to remap via GUI.
    [0] = LAYOUT(
        // row 0
        KC_Q, KC_W, KC_E,
        // row 1
        KC_R, KC_T, KC_Y,
        // row 2
        KC_U, KC_I, KC_O
    )

    // ── To add a layer, copy the block above and change [0] to [1] ──
    // Example:
    // [1] = LAYOUT(
    //     KC_TRNS, KC_TRNS, ...   // KC_TRNS = use layer below
    // )
};

